version: "3.3"

services:

  # send email by http request from ZD
  consult_send:
    build:
      context: .
      dockerfile: Dockerfile-send
    image: consult_sender:consult-mailbot  # name the image 'mailbot'
    container_name: consult_sender
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped

  # check mailbox and update ZD ticket
  consult_receive:
    build:
      context: .
      dockerfile: Dockerfile-receive
    image: consult_receiver:consult-mailbot
    container_name: consult_receiver
    env_file:
      - .env
    restart: unless-stopped

  diffbot:
    build:
      context: .
      dockerfile: Dockerfile-diff
    image: differ:diffbot
    container_name: differ
    env_file:
      - .env
    restart: unless-stopped
