FROM ubuntu:18.04

MAINTAINER Duncan Hall "duncan@archive.org"

RUN apt-get update -y && \
    apt-get install -y python3.7 python3-pip && \
    apt-get install -y cron

COPY * /

RUN pip3 install -r requirements.txt

CMD python3 -u check_mail.py